# pipeline.yaml
enabled_tasks:
  - traffic_light
  - traffic_sign

task:
  traffic_light:
    conf_thres: 0.3
    model_path: "${models.traffic_light.model_path}"  # 引用 models.yaml 中的路径
    input_size: "${models.traffic_light.input_size}"  # 引用 models.yaml 中的输入尺寸
    threshold: "${models.traffic_light.threshold}"
    device: "${models.traffic_light.device}"

  traffic_sign:
    model_path: "models/yolo11s.pt"
    input_size: [640, 640]
    threshold: 0.25  
    device: "cuda"