# pipeline.yaml
enabled_tasks:
  - traffic_light
  - traffic_sign

task:
  traffic_light:
    model_path: "models/tl.onnx"
    input_size: [640, 640]
    threshold: 0.25
    device: "cuda"
  traffic_sign:
    # model_path: "models/yolo11s_ts.pt"
    model_path: "models/ts.onnx"
    input_size: [640, 640]
    threshold: 0.25  
    device: "cuda"